version: "3.9"

networks:
  tini_net:
    driver: bridge

volumes:
  db_data:
  redis_data:

services:
  reverse-proxy:
    build: ./reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tini_net
    depends_on:
      - captive-portal
      - dashboard
      - admin-portal
      - campaign-api
      - tracking-service
  captive-portal:
    build: ./captive-portal
    container_name: captive-portal
    networks:
      - tini_net
    depends_on:
      - campaign-api
      - tracking-service
    environment:
      - API_BASE_URL=http://campaign-api:3000
      - TRACKING_BASE_URL=http://tracking-service:3001

  campaign-api:
    build: ./campaign-api
    container_name: campaign-api
    ports:
      - "3000:3000"
    networks:
      - tini_net
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/wifi_marketing_platform
      - REDIS_URL=redis://cache:6379
    depends_on:
      - database
      - cache

  tracking-service:
    build: ./tracking-service
    container_name: tracking-service
    ports:
      - "3001:3001"
    networks:
      - tini_net
    environment:
      - DATABASE_URL=postgres://postgres:postgres@database:5432/wifi_marketing_platform
      - REDIS_URL=redis://cache:6379
    depends_on:
      - database
      - cache

  dashboard:
    build: ./dashboard
    container_name: dashboard
    networks:
      - tini_net

  admin-portal:
    build: ./admin-portal
    container_name: admin-portal
    networks:
      - tini_net

  database:
    image: postgres:15
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wifi_marketing_platform
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - tini_net

  cache:
    image: redis:7
    container_name: cache
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tini_net