name: tiNi_Wifi CICD

on:
  push:
    branches: [ main ]

jobs:
  ssh-windows:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into Windows and show ipconfig
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 14.161.25.81
          port: 2222
          username: tranthem
          password: NhoDoi@@099112##
          script: |
            echo Da SSH vao Windows
            cmd /c ipconfig /all

      - name: Done
        run: echo "SSH thành công"
