name: CI for tiNi_Wifi update branch

on:
    push:
        branches:
            - update
    pull_requests:
        branches:
            - update

jobs:
    check-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
    validate-docker-compose:
        runs-on: ubuntu-latest
        steps:
            - name: Validate dpcker-compose file
              run: docker compose config
    build-docker-images:
        runs-on: ubuntu-lartest
        needs: validate-docker-compose
        steps:
            - name: Docker compose build and run
              run: docker compose up -d --build
    thong-bao:
        runs-on: ubuntu-latest
        steps:
            - name: Thong bao
              run: echo "CI for tiNi_Wifi update branch đã chạy thành công"





